ibtool --generate-strings-file DocumentViewController-iPad.strings en.lproj/DocumentViewController-iPad.xib
ibtool --generate-strings-file EditMetaDataTableViewCell-iPad.strings en.lproj/EditMetaDataTableViewCell-iPad.xib
ibtool --generate-strings-file EditMetaDataTableViewCell.strings      en.lproj/EditMetaDataTableViewCell.xib
ibtool --generate-strings-file EditMetaDataTableViewCellNotEditable-iPad.strings     en.lproj/EditMetaDataTableViewCellNotEditable-iPad.xib
ibtool --generate-strings-file MainWindow-iPad.strings     en.lproj/MainWindow.xib
ibtool --generate-strings-file MainWindow.strings     en.lproj/MainWindow.xib
ibtool --generate-strings-file MetaDataTableViewCell.strings    en.lproj/MetaDataTableViewCell.xib
ibtool --generate-strings-file RepositoryItemTableViewCell.strings     en.lproj/RepositoryItemTableViewCell.xib
ibtool --generate-strings-file RootViewController.strings     en.lproj/RootViewController.xib
